run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/jasoet/go-wf

  gofumpt:
    extra-rules: true

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  lll:
    line-length: 190
    tab-width: 1

  gocyclo:
    min-complexity: 20

  dupl:
    threshold: 100

  funlen:
    lines: 100
    statements: 50

  godot:
    scope: declarations
    capital: false

  revive:
    rules:
      - name: unexported-return
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: var-naming
        arguments:
          - ["ID", "URL", "HTTP", "API", "JSON", "XML", "HTML", "SQL", "DB", "gRPC", "TCP", "UDP", "IP", "UUID", "URI"]

  staticcheck:
    checks: ["all"]

linters:
  disable-all: true
  enable:
    # Code correctness
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

    # Security
    - gosec

    # Performance
    - prealloc
    - unconvert

    # Style
    - gofmt
    - goimports
    - gofumpt
    - revive
    - misspell
    - godot

    # Complexity
    - gocyclo
    - funlen

    # Bug prevention
    - bodyclose
    - rowserrcheck
    - sqlclosecheck

    # Code quality
    - goconst
    - dupl

issues:
  exclude-use-default: false
  exclude-case-sensitive: false
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - goconst
        - lll
        - errcheck
        - gocyclo
        - funlen
        - dupl

    # Exclude some linters from running on example files
    - path: examples/
      linters:
        - gosec
        - errcheck
        - lll
