name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    name: Lint & Test
    if: >
      github.event_name == 'push' ||
      github.actor == 'jasoet'
    runs-on: [self-hosted, local, macOS, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          set-safe-directory: false

      - name: Lint
        run: nix develop --command task lint

      - name: Test
        run: nix develop --command task ci:test
